name: Check Pull Request Main
on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize]
jobs:
  build_and_testing:
    name: Build and Testing
    runs-on: windows-latest
    steps:
      - name: Preparation
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run Linters
        uses: github/super-linter@v4
        with:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}