name: Check Pull Request Main
on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize]
jobs:
  build_and_testing:
    name: Build and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          skip-cache: true
          skip-build-cache: true
          nolint:errcheck






