name: Check Pull Request Main
on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize]
jobs:
  build_and_testing:
    name: Build and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Go-linter
        uses: Jerome1337/golint-action@v1.0.2




